/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class messaging_core_publisher_Publisher */

#ifndef _Included_messaging_core_publisher_Publisher
#define _Included_messaging_core_publisher_Publisher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     messaging_core_publisher_Publisher
 * Method:    nativeNew
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_messaging_core_publisher_Publisher_nativeNew
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     messaging_core_publisher_Publisher
 * Method:    publish
 * Signature: (JJLjava/lang/String;Ljava/lang/String;JLjava/lang/String;ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_messaging_core_publisher_Publisher_publish
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jlong, jstring, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
